# Generated by Django 4.2 on 2023-10-24 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 16, 16, 9, 677841, tzinfo=datetime.timezone.utc)),
        ),
    ]
